version: "3.7"
services:
  hivemetastore:
    image: postgres:11.5
    hostname: hivemetastore
    environment:
      POSTGRES_PASSWORD: new_password
    expose:
      - 5432
    ports:
      # JDBC 
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      spark_net:
        ipv4_address: 172.28.1.4
    extra_hosts:
      - "master:172.28.1.1"
      - "worker1:172.28.1.2"
      - "worker2:172.28.1.3"
      - "hivemetastore:172.28.1.4"
      - "zeppelin:172.28.1.5"
      - "zoo1:172.28.1.11"
      - "zoo2:172.28.1.12"
      - "zoo3:172.28.1.13"
    
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      spark_net:
        ipv4_address: 172.28.1.11
    extra_hosts:
      - "master:172.28.1.1"
      - "worker1:172.28.1.2"
      - "worker2:172.28.1.3"
      - "hivemetastore:172.28.1.4"
      - "zeppelin:172.28.1.5"
      - "zoo1:172.28.1.11"
      - "zoo2:172.28.1.12"
      - "zoo3:172.28.1.13"
  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      spark_net:
        ipv4_address: 172.28.1.12
    extra_hosts:
      - "master:172.28.1.1"
      - "worker1:172.28.1.2"
      - "worker2:172.28.1.3"
      - "hivemetastore:172.28.1.4"
      - "zoo1:172.28.1.11"
      - "zoo2:172.28.1.12"
      - "zoo3:172.28.1.13"
  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      spark_net:
        ipv4_address: 172.28.1.13
    extra_hosts:
      - "master:172.28.1.1"
      - "worker1:172.28.1.2"
      - "worker2:172.28.1.3"
      - "hivemetastore:172.28.1.4"
      - "zoo1:172.28.1.11"
      - "zoo2:172.28.1.12"
      - "zoo3:172.28.1.13"
      
  master:
    image: nasheb/bigdata:1.0
#    build: '../hadoop-hive-spark-docker'
    hostname: master
    depends_on:
      - hivemetastore
      - zoo1
      - zoo2
      - zoo3
    environment:
      HADOOP_NODE: namenode
      HADOOP_SERVERS_HOSTNAME: master worker1 worker2
      HADOOP_NNAMENADE_HOSTNAME: master
      HBASE_ROLE: hmaster
      HBASE_MASTER_HOSTNAME: master
      HBASE_REGIONSERVER_HOSTNAME: worker1 worker2
      SPARK_PUBLIC_DNS: localhost
      SPARK_LOCAL_IP: 172.28.1.1
      SPARK_MASTER_HOST: 172.28.1.1
      SPARK_LOCAL_HOSTNAME: master
      ZOO_SERVERS_HOSTNAME: zoo1 zoo2 zoo3
      # - SPARK_DEPLOY_MODE=client
      SPARK_MASTER: yarn
      LOCAL_DIR_WHITELIST: /data/batches/
      ENABLE_HIVE_CONTEXT: "false"
      # Defaults are fine for variables below. Uncomment to change them.
    expose:
      - 1-65535
    ports:
      # Spark Master Web UI
      - 8080:8080
      # Spark job Web UI: increments for each successive job
      - 4040:4040
      - 4041:4041
      - 4042:4042
      - 4043:4043
      # Spark History server
      - 18080:18080
      # YARN UI
      - 8088:8088
      # YARN LOG SERVER UI
      - 19888:19888
      # Hadoop namenode UI
      - 9870:9870
      # Hadoop secondary namenode UI
      - 9868:9868
      # Hive JDBC
      - 10000:10000
      # HBase UI
      - 16010:16010
      # Flink UI
      - 45080:45080
      # Flink JobManager
      - 10020:10020
    volumes:
      - ./data:/data
      - ./data_share:/data_share
      - ./logs/hadoop:/usr/program/hadoop/logs
      - ./logs/hbase:/usr/program/hbase/logs
      - ./logs/hive:/usr/program/hive/logs
      - ./logs/spark:/usr/program/spark/logs
      - ./logs/flink:/usr/program/flink/logs
    networks:
      spark_net:
        ipv4_address: 172.28.1.1
    extra_hosts:
      - "master:172.28.1.1"
      - "worker1:172.28.1.2"
      - "worker2:172.28.1.3"
      - "hivemetastore:172.28.1.4"
      - "zoo1:172.28.1.11"
      - "zoo2:172.28.1.12"
      - "zoo3:172.28.1.13"

  worker1:
    image: nasheb/bigdata:1.0
#    build: '../hadoop-hive-spark-docker'
    hostname: worker1
    depends_on:
      - hivemetastore
    environment:
      HADOOP_NODE: datanode
      HADOOP_NNAMENADE_HOSTNAME: master
      HADOOP_SERVERS_HOSTNAME: master worker1 worker2
      HBASE_ROLE: regionserver
      HBASE_MASTER_HOSTNAME: master
      HBASE_REGIONSERVER_HOSTNAME: worker1 worker2
      SPARK_MASTER_ADDRESS: spark://master:7077
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8981
      SPARK_PUBLIC_DNS: localhost
      SPARK_LOCAL_HOSTNAME: worker1
      SPARK_LOCAL_IP: 172.28.1.2
      SPARK_MASTER_HOST: 172.28.1.1
      HADOOP_DATANODE_UI_PORT: 9864
      ZOO_SERVERS_HOSTNAME:  zoo1 zoo2 zoo3
    expose:
      - 1-65535
    ports:
      # Hadoop datanode UI
      - 9864:9864
      #Spark worker UI
      - 8981:8981
      # Spark Job UI
      - 8101:8042
      # Flink UI
      - 45081:45080
    volumes:
      - ./data:/data
      - ./logs/hadoop:/usr/program/hadoop/logs
      - ./logs/hbase:/usr/program/hbase/logs
      - ./logs/hive:/usr/program/hive/logs
      - ./logs/spark:/usr/program/spark/logs
    networks:
      spark_net:
        ipv4_address: 172.28.1.2
    extra_hosts:
      - "master:172.28.1.1"
      - "worker1:172.28.1.2"
      - "worker2:172.28.1.3"
      - "hivemetastore:172.28.1.4"
      - "zoo1:172.28.1.11"
      - "zoo2:172.28.1.12"
      - "zoo3:172.28.1.13"

  worker2:
    image: nasheb/bigdata:1.0
#    build: '../hadoop-hive-spark-docker'
    hostname: worker2
    depends_on:
      - hivemetastore
    environment:
      HADOOP_NNAMENADE_HOSTNAME: master
      HADOOP_SERVERS_HOSTNAME: master worker1 worker2
      HBASE_ROLE: regionserver thrift
      HBASE_MASTER_HOSTNAME: master
      HBASE_REGIONSERVER_HOSTNAME: worker1 worker2
      SPARK_MASTER_ADDRESS: spark://master:7077
      SPARK_WORKER_PORT: 8882
      SPARK_WORKER_WEBUI_PORT: 8982
      SPARK_PUBLIC_DNS: localhost
      SPARK_LOCAL_HOSTNAME: worker2
      SPARK_LOCAL_IP: 172.28.1.3
      SPARK_MASTER_HOST: 172.28.1.1
      HADOOP_NODE: datanode
      HADOOP_DATANODE_UI_PORT: 9865
      ZOO_SERVERS_HOSTNAME:  zoo1 zoo2 zoo3
    expose:
      - 1-65535
    ports:
      # Hadoop datanode UI
      - 9865:9865
      # Spark worker UI
      - 8982:8982
      # Spark Job UI
      - 8102:8042
      # Flink UI
      - 45082:45080
    volumes:
      - ./data:/data
      - ./logs/hadoop:/usr/program/hadoop/logs
      - ./logs/hbase:/usr/program/hbase/logs
      - ./logs/hive:/usr/program/hive/logs
      - ./logs/spark:/usr/program/spark/logs
    networks:
      spark_net:
        ipv4_address: 172.28.1.3
    extra_hosts:
      - "master:172.28.1.1"
      - "worker1:172.28.1.2"
      - "worker2:172.28.1.3"
      - "hivemetastore:172.28.1.4"
      - "zoo1:172.28.1.11"
      - "zoo2:172.28.1.12"
      - "zoo3:172.28.1.13"

networks:
  spark_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
volumes:
  data_share:

