version: '2'
services:
  zookeeper:
    image: nasheb/zookeeper:1.0
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: nasheb/kafka:1.0
    build: .
    ports:
      - "9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: ip-172-31-45-112.us-east-2.compute.internal
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
