version: '3'
services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
     - "8443:8443"
    volumes:
      - nifi_data:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content:/opt/nifi/nifi-current/content_repository
      - nifi_provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi_conf:/opt/nifi/nifi-current/conf
    environment:
      - NIFI_WEB_PROXY_HOST=3.134.216.46:8443
volumes:
  nifi_data:
    driver: local
  nifi_flowfile:
    driver: local
  nifi_content:
    driver: local
  nifi_provenance:
    driver: local
  nifi_conf:
    driver: local
