services:
  zookeeper:
    image: nasheb/zookeeper:1.0
    ports:
      - "2181:2181"
    restart: unless-stopped

  # ----------------------------
  # Single-broker (default)
  # ----------------------------
  kafka:
    profiles: ["single"]
    image: nasheb/kafka:1.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_OPTS: "-XX:-UseContainerSupport -Dcom.sun.management.jmxremote=false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: "1"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    restart: unless-stopped

  # ----------------------------
  # 3-broker cluster profile
  # ----------------------------
  kafka1:
    profiles: ["cluster"]
    image: nasheb/kafka:1.0
    depends_on:
      - zookeeper
    ports:
      - "9092:19092"
    environment:
      KAFKA_OPTS: "-XX:-UseContainerSupport -Dcom.sun.management.jmxremote=false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: "1"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

    restart: unless-stopped

  kafka2:
    profiles: ["cluster"]
    image: nasheb/kafka:1.0
    depends_on:
      - zookeeper
    ports:
      - "9093:19092"
    environment:
      KAFKA_OPTS: "-XX:-UseContainerSupport -Dcom.sun.management.jmxremote=false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: "2"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9092,EXTERNAL://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

    restart: unless-stopped

  kafka3:
    profiles: ["cluster"]
    image: nasheb/kafka:1.0
    depends_on:
      - zookeeper
    ports:
      - "9094:19092"
    environment:
      KAFKA_OPTS: "-XX:-UseContainerSupport -Dcom.sun.management.jmxremote=false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: "3"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:9092,EXTERNAL://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

    restart: unless-stopped